# 选择一个基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制并安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt



# 启动命令（生产用 Gunicorn，也可以换成 flask run）
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]
